apiVersion: v1
kind: Service
metadata:
 name: sample-akiyama-server
 labels:
   name: sample-akiyama-server
spec:
 ports:
 - port: 8080
   targetPort: 8080
 type: NodePort
 selector:
   name: sample-akiyama-server